app/urls.py
from django.urls import path
from .views import LenscrowDataListView, DisbursementDataListView, HomeView, register

app_name = "app"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('register/', register, name='register'),
    path('lenscrow/list', LenscrowDataListView.as_view(),
         name="lenscrow_data_list"),

#     path('disbursement/import', DisbursementDataImportView.as_view(),
#          name="disbursement_data_import"),
    path('disbursement/list', DisbursementDataListView.as_view(),
         name="disbursement_data_list"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>File Reader</title>
    <!-- Bootstrap -->
    {% comment %}
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'Css/main.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'app:home' %}">
            <h2>File Reader     </h2></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            {% comment %} <h3 class="active">{% block page %}{% endblock page %}</h3> {% endcomment %}
            <a class="mr-3 active " href="">{% block page %}{% endblock page %}</a>

            {% comment %} <ul class="navbar-nav mr-auto">
                <li class="nav-item {% block lenscrow %}{% endblock %}">
                    <a class="nav-link" href="{% url 'app:lenscrow_data_list' %}">Lenscrow <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% block disbursement %}{% endblock %}">
                    <a class="nav-link" href="{% url 'app:disbursement_data_list' %}">Disbursement</a>
                </li>
            </ul> {% endcomment %}
            {% comment %} <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> {% endcomment %}
        </div>


        {% if request.user.is_authenticated %}

        <a class="mr-3 {% block home %}{% endblock home %}" href="{% url 'app:home' %}">Home</a>


        <a class="mr-3 {% block register %}{% endblock register %}" href="{% url 'app:register' %}">Register User</a>

        <div class="userprofile">
            <h3 class="mr-3 profileBtn">{{request.user.username|title}}</h3>
            <div class="userDropdown ">
                {% comment %} <a href="">
                    <div class="d-flex align-items-center" style="gap: 8px;">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                            aria-hidden="true" role="img" width="1em" height="1em" preserveAspectRatio="xMidYMid meet"
                            viewBox="0 0 24 24">
                            <path fill="currentColor"
                                d="M12 2A10.13 10.13 0 0 0 2 12a10 10 0 0 0 4 7.92V20h.1a9.7 9.7 0 0 0 11.8 0h.1v-.08A10 10 0 0 0 22 12A10.13 10.13 0 0 0 12 2zM8.07 18.93A3 3 0 0 1 11 16.57h2a3 3 0 0 1 2.93 2.36a7.75 7.75 0 0 1-7.86 0zm9.54-1.29A5 5 0 0 0 13 14.57h-2a5 5 0 0 0-4.61 3.07A8 8 0 0 1 4 12a8.1 8.1 0 0 1 8-8a8.1 8.1 0 0 1 8 8a8 8 0 0 1-2.39 5.64z" />
                            <path fill="currentColor"
                                d="M12 6a3.91 3.91 0 0 0-4 4a3.91 3.91 0 0 0 4 4a3.91 3.91 0 0 0 4-4a3.91 3.91 0 0 0-4-4zm0 6a1.91 1.91 0 0 1-2-2a1.91 1.91 0 0 1 2-2a1.91 1.91 0 0 1 2 2a1.91 1.91 0 0 1-2 2z" />
                        </svg>
                      {{ request.user.username }}
                      
                    </div>
                </a> {% endcomment %}
                <a class="" href="{% url 'logout' %}">
                    <div class="d-flex align-items-center logout" style="gap: 8px;">
                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
                            aria-hidden="true" role="img" width="1em" height="1em" preserveAspectRatio="xMidYMid meet"
                            viewBox="0 0 1024 1024">
                            <path fill="currentColor"
                                d="M868 732h-70.3c-4.8 0-9.3 2.1-12.3 5.8c-7 8.5-14.5 16.7-22.4 24.5a353.84 353.84 0 0 1-112.7 75.9A352.8 352.8 0 0 1 512.4 866c-47.9 0-94.3-9.4-137.9-27.8a353.84 353.84 0 0 1-112.7-75.9a353.28 353.28 0 0 1-76-112.5C167.3 606.2 158 559.9 158 512s9.4-94.2 27.8-137.8c17.8-42.1 43.4-80 76-112.5s70.5-58.1 112.7-75.9c43.6-18.4 90-27.8 137.9-27.8c47.9 0 94.3 9.3 137.9 27.8c42.2 17.8 80.1 43.4 112.7 75.9c7.9 7.9 15.3 16.1 22.4 24.5c3 3.7 7.6 5.8 12.3 5.8H868c6.3 0 10.2-7 6.7-12.3C798 160.5 663.8 81.6 511.3 82C271.7 82.6 79.6 277.1 82 516.4C84.4 751.9 276.2 942 512.4 942c152.1 0 285.7-78.8 362.3-197.7c3.4-5.3-.4-12.3-6.7-12.3zm88.9-226.3L815 393.7c-5.3-4.2-13-.4-13 6.3v76H488c-4.4 0-8 3.6-8 8v56c0 4.4 3.6 8 8 8h314v76c0 6.7 7.8 10.5 13 6.3l141.9-112a8 8 0 0 0 0-12.6z" />
                        </svg>
                        <p>Logout</p>
                    </div>
                </a>
            </div>
        </div>



        {% endif %}
    </nav>
    {% block content %} {% endblock content %}


    <script>
        const userDropdown = () => {
            const btn = document.querySelector(".profileBtn");
            const dropdown = document.querySelector(".userDropdown");
            btn.addEventListener("click", function (e) {
                e.stopPropagation();
                dropdown.classList.toggle("active")

            });
            window.addEventListener("click", function (e) {
                if (dropdown.classList.contains("active")) {
                    dropdown.classList.remove("active");
                    console.log("sad");
                }
                else {
                    console.log("sad");
                }

            })


        }
        userDropdown();
    </script>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    {% block javascript %} {% endblock javascript %}
</body>

</html>